#!/bin/bash
DATE=$1
num=0
STATIC_JSON='{"balis":1}'
RIDERID=10000000
SHOPID=50000000
MYSQL='mysql -h127.0.0.1 -P5555 -ubalis -pbalis -Ddatabasename'
case $2 in
   1)
     num=10000
   ;;
   2)
     num=20000
   ;;
   *)
     num=600
   ;;
esac
echo "insert num is $num"
echo "delete from balis_table"| `$MYSQL`
for k in `seq 1 $num`
do
    ((RIDERID=$RIDERID+1))
    ((SHOPID=$SHOPID+1))
    echo "insert into balis_table (shop_id, delivery_id, dt) values ($SHOPID,$RIDERID,'$DATE')" | $($MYSQL)
    if [ $? -ne 0 ]; then
        break
    fi
done
echo "done with riderid:$RIDERID, shopid:$SHOPID"
